apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: kubevirt
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: kubevirt
  project: default
  sources:
  - directory:
      jsonnet: {}
      recurse: true
    path: applications/kubevirt/extra
    repoURL: git@github.com:jsmcnair/homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata: {}
    syncOptions:
    - CreateNamespace=true
status:
  health: {}
  sourceHydrator: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
