apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
spec:
  secretStoreRef:
    name: bootstrap
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: bootstrap
        property: tailscale-oauth-client-id
    - secretKey: client_secret
      remoteRef:
        key: bootstrap
        property: tailscale-oauth-client-secret