apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: juicefs-keydb
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  sources:
  - chart: keydb
    helm:
      parameters:
      - name: replica.activeReplica
        value: "true"
      - name: auth.enabled
        value: "false"
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 0.5.4
  - chart: juicefs-csi-driver
    helm:
      valuesObject:
        immutable: "true"
    repoURL: https://juicedata.github.io/charts
    targetRevision: v0.28.1
  - directory:
      jsonnet: {}
      recurse: true
    path: applications/juicefs-keydb/extra
    repoURL: git@github.com:jsmcnair/homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
    - CreateNamespace=true
status:
  health: {}
  sourceHydrator: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
