apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: storj-token
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: storj
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: storj-juicefs