apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: cert-manager
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  project: default
  sources:
  - chart: cert-manager
    helm:
      parameters:
      - name: crds.enabled
        value: "true"
    repoURL: https://charts.jetstack.io
    targetRevision: v1.17.1
  - directory:
      jsonnet: {}
      recurse: true
    path: applications/cert-manager/extra
    repoURL: git@github.com:jsmcnair/homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata: {}
    syncOptions:
    - CreateNamespace=true
status:
  health: {}
  sourceHydrator: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
