generators:
  - name: cert-manager
    type: argocd
    namespace: cert-manager
    enableExtraManifestSource: true
    sources:
      - repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.17.1
        helm:
          parameters:
            - name: crds.enabled
              value: "true"
