apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: default
  sources:
  - chart: ingress-nginx
    helm:
      valuesObject:
        controller:
          service:
            annotations:
              tailscale.com/expose: "true"
              tailscale.com/hostname: infra
            enabled: true
            type: ClusterIP
          watchIngressWithoutClass: true
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: v4.12.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata: {}
    syncOptions:
    - CreateNamespace=true
status:
  health: {}
  sourceHydrator: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
