apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination: 
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: v4.12.2
      helm:
        valuesObject:
          controller:
            watchIngressWithoutClass: true
            service:
              enabled: true
              type: ClusterIP
              annotations:
                tailscale.com/expose: "true"
                tailscale.com/hostname: infra
    - repoURL: git@github.com:jsmcnair/homelab
      path: applications/ingress-nginx
      directory:
        exclude: application.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
