apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-storj
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: velero-storj
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: velero-storj
    