apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: external-secrets
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: external-secrets
  project: default
  sources:
  - chart: external-secrets
    helm:
      parameters:
      - name: bitwarden-sdk-server.enabled
        value: "true"
    repoURL: https://charts.external-secrets.io
    targetRevision: v0.16.1
  - directory:
      jsonnet: {}
      recurse: true
    path: applications/external-secrets/extra
    repoURL: git@github.com:jsmcnair/homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata: {}
    syncOptions:
    - CreateNamespace=true
status:
  health: {}
  sourceHydrator: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
