apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  destination: 
    namespace: external-secrets
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: v0.15.0
    - repoURL: git@github.com:jsmcnair/homelab
      path: applications/external-secrets
      directory:
        exclude: application.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    
