apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bootstrap
spec:
  provider:
    kubernetes:
      remoteNamespace: external-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: external-secrets
          key: ca.crt
      auth:
        serviceAccount: 
          name: external-secrets
          namespace: external-secrets