apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  destination: 
    namespace: openebs
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://openebs.github.io/openebs
      chart: openebs
      targetRevision: v4.2.0
      helm:
        values: |
          engines:
            local:
              lvm:
                enabled: "false"
              zfs:
                enabled: "false"
          mayastor:
            csi:
              node:
                initContainers:
                  enabled: false
            io_engine:
              envcontext: iova-mode=pa
    - repoURL: git@github.com:jsmcnair/homelab
      path: applications/openebs
      directory:
        exclude: application.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged