apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-root-secret
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: minio-root-secret
    creationPolicy: Owner
  data:
    - secretKey: config.env
      remoteRef:
        key: minio-root-secret