apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localpath-provisioner
  namespace: argocd
spec:
  project: default
  destination: 
    namespace: localpath-provisioner
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/rancher/local-path-provisioner
      targetRevision: v0.0.31
      path: deploy
      kustomize: 
        patches:
          - target:
              kind: ConfigMap
              name: local-path-config
            patch: |-
              - op: replace
                path: /data/config.json
                value: |-
                  {
                    "nodePathMap":[{
                      "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                      "paths":["/var/local-path-provisioner"]
                    }]
                  }
          - target:
              kind: StorageClass
              name: local-path
            patch: |-
              - op: add
                path: /metadata/annotations/storageclass.kubernetes.io~1is-default-class
                value: "true"
    - repoURL: git@github.com:jsmcnair/homelab
      path: applications/localpath-provisioner
      directory:
        exclude: application.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
