apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: k8s-monitoring
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: k8s-monitoring
  project: default
  sources:
  - chart: k8s-monitoring
    helm:
      valueFiles:
      - $values/applications/k8s-monitoring/values.yaml
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: v2.1.4
  - ref: values
    repoURL: git@github.com:jsmcnair/homelab
  - directory:
      jsonnet: {}
      recurse: true
    path: applications/k8s-monitoring/extra
    repoURL: git@github.com:jsmcnair/homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
    - CreateNamespace=true
status:
  health: {}
  sourceHydrator: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
