generators:
  - name: k8s-monitoring
    type: argocd
    namespace: k8s-monitoring
    enableExtraManifestSource: true
    privilegedNamespace: true
    sources:
      - repoURL: https://grafana.github.io/helm-charts
        chart: k8s-monitoring
        targetRevision: v2.1.4
        helm:
          valueFiles:
            - $values/applications/k8s-monitoring/values.yaml
      - repoURL: git@github.com:jsmcnair/homelab
        ref: values
