apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-cloud
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: grafana-cloud
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: grafana-cloud-infra-k8s-token
    - secretKey: prometheus-username
      remoteRef:
        key: grafana-cloud-infra-k8s-prometheus-username
    - secretKey: loki-username
      remoteRef:
        key: grafana-cloud-infra-k8s-loki-username
    - secretKey: otlp-username
      remoteRef:
        key: grafana-cloud-infra-k8s-otlp-username