cluster:
  name: infra
destinations:
  - name: grafana-cloud-metrics
    type: prometheus
    url: https://prometheus-prod-55-prod-gb-south-1.grafana.net./api/prom/push
    auth:
      type: basic
      usernameKey: prometheus-username
      passwordKey: token
    secret:
      create: false
      name: grafana-cloud
      namespace: k8s-monitoring
  - name: grafana-cloud-logs
    type: loki
    url: https://logs-prod-035.grafana.net./loki/api/v1/push
    auth:
      type: basic
      usernameKey: loki-username
      passwordKey: token
    secret:
      create: false
      name: grafana-cloud
      namespace: k8s-monitoring
  - name: grafana-cloud-otlp-endpoint
    type: otlp
    url: https://otlp-gateway-prod-gb-south-1.grafana.net./otlp
    protocol: http
    auth:
      type: basic
      usernameKey: otlp-username
      passwordKey: token
    secret:
      create: false
      name: grafana-cloud
      namespace: k8s-monitoring
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true
clusterMetrics:
  enabled: true
  kepler:
    enabled: true
prometheusOperatorObjects:
  enabled: true
clusterEvents:
  enabled: true
podLogs:
  enabled: true
applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
alloy-metrics:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: grafana-cloud
            key: token
      - name: CLUSTER_NAME
        value: infra
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-023.grafana.net
    auth:
      type: basic
      usernameKey: otlp-username
      passwordKey: token
    secret:
      create: false
      name: grafana-cloud
      namespace: k8s-monitoring
alloy-singleton:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: grafana-cloud
            key: token
      - name: CLUSTER_NAME
        value: infra
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-023.grafana.net
    auth:
      type: basic
      usernameKey: otlp-username
      passwordKey: token
    secret:
      create: false
      name: grafana-cloud
      namespace: k8s-monitoring
alloy-logs:
  enabled: true
  alloy:
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: grafana-cloud
            key: token
      - name: CLUSTER_NAME
        value: infra
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-023.grafana.net
    auth:
      type: basic
      usernameKey: otlp-username
      passwordKey: token
    secret:
      create: false
      name: grafana-cloud
      namespace: k8s-monitoring
alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
    extraEnv:
      - name: GCLOUD_RW_API_KEY
        valueFrom:
          secretKeyRef:
            name: grafana-cloud
            key: token
      - name: CLUSTER_NAME
        value: infra
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: GCLOUD_FM_COLLECTOR_ID
        value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
  remoteConfig:
    enabled: true
    url: https://fleet-management-prod-023.grafana.net
    auth:
      type: basic
      usernameKey: otlp-username
      passwordKey: token
    secret:
      create: false
      name: grafana-cloud
      namespace: k8s-monitoring