generators:
  - name: longhorn
    type: argocd
    namespace: longhorn
    privilegedNamespace: true
    sources:
      - repoURL: https://charts.longhorn.io
        chart: longhorn
        targetRevision: v1.9.0
        helm:
          valuesObject:
            preUpgradeChecker:
              jobEnabled: false
            longhornUI:
              replicas: 1
            ingress:
              enabled: true
              host: longhorn.infra.turong.dev
              tls: true
              annotations:
                external-dns.alpha.kubernetes.io/target: infra.tailf36795.ts.net
                cert-manager.io/cluster-issuer: letsencrypt
            defaultSettings:
              defaultDataPath: /var/mnt/longhorn-nvme
    ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
          - /spec/preserveUnknownFields
