apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: storj-longhorn-backups
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    name: storj-longhorn-backups
    creationPolicy: Owner
    template:
      metadata:
        labels:
          juicefs.com/validate-secret: "true"
  dataFrom:
    - extract:
        key: storj-longhorn-backups