apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: clusterapi-operator
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: capi-operator
  project: default
  sources:
  - chart: cluster-api-operator
    helm:
      valueFiles:
      - $values/applications/clusterapi-operator/values.yaml
    repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
    targetRevision: 0.21.0
  - ref: values
    repoURL: git@github.com:jsmcnair/homelab
  - directory:
      jsonnet: {}
      recurse: true
    path: applications/clusterapi-operator/extra
    repoURL: git@github.com:jsmcnair/homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata: {}
    syncOptions:
    - CreateNamespace=true
status:
  health: {}
  sourceHydrator: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
