generators:
  - name: clusterapi-operator
    type: argocd
    namespace: capi-operator
    sources:
      - repoURL: https://kubernetes-sigs.github.io/cluster-api-operator
        chart: cluster-api-operator
        targetRevision: 0.21.0
        helm:
          valueFiles:
            - $values/applications/clusterapi-operator/values.yaml
      - repoURL: git@github.com:jsmcnair/homelab
        ref: values
    enableExtraManifestSource: true