apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
  namespace: argocd
spec:
  project: default
  destination: 
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph
      targetRevision: v1.17.2
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph-cluster
      targetRevision: v1.17.2
      helm:
        valueFiles:
          - $values/applications/rook-ceph/ceph-cluster-values.yaml
    - repoURL: git@github.com:jsmcnair/homelab
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/warn: privileged
  